CREATE TABLE IF NOT EXISTS ``posts_%s`` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `thread` int(11) DEFAULT NULL,
  `subject` varchar(100) DEFAULT NULL,
  `email` varchar(30) DEFAULT NULL,
  `name` varchar(35) DEFAULT NULL,
  `trip` varchar(15) DEFAULT NULL,
  `capcode` varchar(50) DEFAULT NULL,
  `body` text NOT NULL,
  `body_nomarkup` text,
  `time` int(11) NOT NULL,
  `bump` int(11) DEFAULT NULL,
  `files` text,
  `num_files` int(11) DEFAULT '0',
  `filehash` text CHARACTER SET ascii,
  `password` varchar(64) DEFAULT NULL,
  `ip` varchar(61) CHARACTER SET ascii NOT NULL,
  `cookie` varchar(40) CHARACTER SET ascii NOT NULL,
  `sticky` int(1) NOT NULL,
  `locked` int(1) NOT NULL,
  `cycle` int(1) NOT NULL,
  `sage` int(1) DEFAULT 0 NOT NULL,
  `hideid` int(1) NOT NULL,
  `shadow` int(1) DEFAULT 0 NOT NULL,
  `archive` int(1) DEFAULT 0 NOT NULL,
  `embed` text,
  `slug` varchar(256) DEFAULT NULL,
  `flag_iso` varchar(6) DEFAULT NULL,
  `flag_ext` varchar(100) DEFAULT NULL,
  UNIQUE KEY `id` (`id`),
  KEY `thread_id` (`thread`,`id`),
  KEY `filehash` (`filehash`(40)),
  KEY `time` (`time`),
  KEY `ip` (`ip`),
  KEY `list_threads` (`thread`,`sticky`,`bump`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
